# Dados de conexão com o banco H2
spring.datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password:

# Configuração do cliente web do banco H2
spring.h2:
  console:
    enabled: true
    path: /h2-console

# Configuração para mostrar o SQL no console
spring.jpa:
  show-sql: true
  properties: 
    hibernate.format_sql: true